"""
Django settings for tan_air project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e$7kwnpuvj-p9ab@816$@mx3_te(6%wop%2jwtx06&hwavx)yx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist', 
    'django_filters',
    'myusers',
    'OrderService',
    'djoser'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tan_air.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tan_air.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'tanair',
        'USER': 'postgres',
        'PASSWORD': 'nuhusaidi',
        'HOST': 'localhost',
        'PORT': '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'myusers.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

SIMPLE_JWT = {
    'LOGIN_FIELD': 'email',
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'BLACKLIST_AFTER_ROTATION' : True,

    # #custom
    # "AUTH_COOKIE": "access_token",  
    # "AUTH_COOKIE_DOMAIN": None,  
    # "AUTH_COOKIE_SECURE": False,  
    # "AUTH_COOKIE_HTTP_ONLY": True,  
    # "AUTH_COOKIE_PATH": "/",  
    # "AUTH_COOKIE_SAMESITE": "Lax",  
}

#djoser configurations
DJOSER = {
    'LOGIN_FIELD': 'email',
    'ACTIVATION_URL' : 'activate?uid={uid}&token={token}',
    "SEND_ACTIVATION_EMAIL": False,
    'SEND_CONFIRMATION_EMAIL': False,
    "PASSWORD_RESET_CONFIRM_URL": 'reset-password?uid={uid}&token={token}',
    'PASSWORD_RESET_CONFIRM_RETYPE': True,
    'PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND': True,
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION':True,
    'SET_PASSWORD_RETYPE': True,
    'SERIALIZERS':{
        'user_create': 'myusers.serializers.UserCreaterSerializer',
        'current_user': 'myusers.serializers.CurrentUserSerializer',
    },
    # 'EMAIL': {
    #     'activation': 'learning_system.email.ActivationEmail',
    #     'confirmation': 'learning_system.email.ConfirmationEmail',
    #     'password_reset': 'learning_system.email.PasswordResetEmail',
    #     'password_changed_confirmation': 'learning_system.email.PasswordChangedConfirmationEmail',
    # },
}

CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:3000',
    'http://localhost:3000',
]

EMAIL_HOST = os.getenv("MAILSENDER_SMTP_SERVER")
EMAIL_HOST_USER = os.getenv("MAILSENDER_SMTP_USERNAME")
EMAIL_HOST_PASSWORD = os.getenv("MAILSENDER_SMTP_PASSWORD")
EMAIL_PORT = os.getenv("MAILSENDER_SMTP_PORT")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_USE_TLS = True

DOMAIN = ("localhost:3000") #local: localhost:3000
SITE_NAME = ('localhost:3000')